### ISSUE TITLE
Not receiving verification email

### ISSUE THREAD

**Issue by farhan-helmy** [cleaniquecoders/mediabox-issues#2]

**Comment by nasrulhazim** [comment]
can double check again @farhan-helmy ? it's slightly delayed with sparkpost.

**Comment by farhan-helmy** [comment]
still didnt receive,

**Comment by nasrulhazim** [comment]
weird. cause in sparkpost dashboard can see email delivery. 🤔🤔🤔

**Comment by nasrulhazim** [comment]
closing, email found in Promotion category. ahahha
